# connection info vars
# `ansible-vault encrypt_string`
ansible_user: ubuntu
ansible_become_password: password

timezone: "Asia/Tokyo"

repository_keys_path: "/usr/share/keyrings"
repository_sources_path: "/etc/apt/sources.list.d"
repository_preferences_path: "/etc/apt/preferences.d/"
cpu_architecture: "amd64"

db:
  password: password
  database_name: wordpress
  username: wpuser
  host: localhost

install_phpmyadmin: yes

self_sign: no
# domain_name: "vagrant-akatsuki.myhome.localnet"
domain_name: "{{ ansible_default_ipv4.address }}"
