---
- name: "change document root"
  lineinfile:
    path: "/etc/apache2/sites-available/000-default.conf"
    state: present
    regexp: '^.*DocumentRoot.*$'
    line: "        DocumentRoot /var/www"

- name: "enable ssl(self-sign)"
  include_tasks: self_sign.yaml
  when: self_sign == True

- name: "enable rewrite module"
  shell: "a2enmod rewrite"
  notify: "restart apache"
