---
- name: Create database user with all database privileges
  mysql_user:
    login_user: root
    login_password: "{{ db.password }}"
    name: "{{ db.username }}"
    password: "{{ db.password }}"
    priv: '*.*:ALL'
    host: 'localhost'
    state: present

- name: Try to create database as {{ db.username }}/nopassword first. If not allowed, pass the credentials
  mysql_db:
    login_user: "{{ db.username }}"
    login_password: "{{ db.password }}"
    name: "{{ db.database_name }}"
    state: present
    encoding: utf8mb4
    collation: utf8mb4_general_ci
  notify: "restart mariaDB"


- name: "check php verison"
  shell: "php --version | head -n 1 | awk -F ' ' '{print $2}' | sed -r 's%^([0-9].[0-9]).*%\\1%'"
  register: php_version_result

- name: "create apache conf"
  template:
    src: wordpress.conf.j2
    dest: "{{ wp_apache_dir }}/wordpress.conf"
  notify: "restart apache"

# - name: "link config file"
#   file:
#     state: link
#     src: "{{ wp_apache_dir }}/wordpress.conf"
#     dest: /etc/nginx/sites-enabled/wordpress.conf
#   notify: "restart nginx"

- name: "wp-config"
  template:
    src: "wp-config.php.j2"
    dest: "{{ wordpress.installpath }}/wp-config.php"
  notify: "chmodown wordpress dir"

- name: "chown wordpress www-data"
  file:
    path: "{{ wordpress.installpath }}"
    owner: "www-data"
    recurse: yes
