---
# - name: "mkdir {{ wordpress.installpath }}"
#   file:
#     path: "{{ wordpress.installpath }}"
#     state: "directory"

- name: "Get stats of a /tmp/wordpress"
  stat:
    path: /tmp/wordpress
    get_attributes: no
  register: tmpwp

- name: "dl & unpack wordpress"
  unarchive:
    src: "https://ja.wordpress.org/latest-ja.tar.gz"
    dest: "/tmp"
    owner: "root"
    group: "root"
    remote_src: yes
  when: tmpwp.stat.exists == False

- name: "copy wordpress"
  copy:
    remote_src: yes
    src: "/tmp/wordpress"
    dest: "{{ wwwroot }}"
    owner: "root"
    group: "www-data"
    force: no

- name: "install libapache2-mod-php"
  apt:
    name: "libapache2-mod-php"
